### ISSUE TITLE
attempt to perform arithmetic on global 'forward' (a nil value)

### ISSUE THREAD

**Issue by kkharji** [jbyuki/nabla.nvim#34] opened 2022-07-26 19:19 UTC
Hey @jbyuki, 

I'm using nabla after along time, I'm used to nabla.action to toggle the view. Now when I call it I get 

```
...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:879: attempt to perform arithmetic on global 'forward' (a nil value)
```

Any ideas what may be causing this

Thanks

**Comment by jbyuki** [comment] 2022-07-27 09:53
Please try with the new version. I committed some changes to support back these functionalities.

**Comment by kkharji** [comment] 2022-07-27 16:39
Thanks @jbyuki. 

it worked the first time but then 

```rust
E5108: Error executing lua ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:969: start is higher than end
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:969: in function 'replace_this'
        ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:597: in function 'action'
        [string ":lua"]:1: in main chunk
```

test
```
$\frac{1}{2} + \frac{1}{3}$
```

btw, I tried to exit then the same error above but I hit no for not save changes and now  a full day work gone 😭, I didn't add it to git and :recover didn't do anything, sh##t

**Comment by jbyuki** [comment] 2022-07-28 04:40
Damn sorry, that's why I removed the old functionality  because it seemed too dangerous. So sorry.
I will still have a look when I can.

**Comment by jbyuki** [comment] 2022-07-31 14:37
I fixed the issue, it should work now. Please check on your side.
BUT this is not advised to use, as it is a destructive feature, as you noticed.

I hope virtual multi-line come one day.

**Comment by kkharji** [comment] 2022-08-01 15:50
@jbyuki perfect toggling works with no issues. Thanks so much. 

I like this way of writing and displaying, it's in my opinion much more convenient then say wrapping it with latex codeblock. This is way not so hyped about virtual multi line as it would mean having latex in docs. However, when working with html and custom render of latex then maybe.

Btw, not sure if you've seen that diagnostics plugin that shows multi virtual lines, tired to hunt for it but failed to find it. I will post it here when I come across it.

**Comment by kkharji** [comment] 2022-08-01 16:40
When attempting to transform from the end of the line, I get another artithmetic error

```
E5108: Error executing nabla.lua:836: attempt to perform arithmetic on local 'srow' (a nil value)
``` 

would be hard to have work? it works if the cursor is one char before then end of the line.

**Comment by kkharji** [comment] 2022-08-01 18:45
`Error executing lua ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:604: Expected lua number`

This happens when no formula is found in current line, it would be nice if `nvim_buf_get_extmarks` is skipped when the nothing found

**Comment by jbyuki** [comment] 2022-08-01 18:47
> would be hard to have work? it works if the cursor is one char before then end of the line.

This was brought up by somebody in issue #33 . Never got an answer so I didn't implement.
But why not do it this time. It should be fairly straightforward and more logical from an user's perspective.
I will try push a commit when I have some time.

> This happens when no formula is found in current line, it would be nice if nvim_buf_get_extmarks is skipped when the nothing found

Could you explain in more details?

**Comment by kkharji** [comment] 2022-08-01 18:59
> Could you explain in more details?

sorry about, try executing nabla.action on empty line or a line that doesn't have latex

**Comment by jbyuki** [comment] 2022-08-01 19:01
Ok, I will also make the error disappear in this case for the next commit.

**Comment by kkharji** [comment] 2022-08-01 19:27
❤️

**Comment by jbyuki** [comment] 2022-08-01 20:19
I just saw on this week in neovim, is that the diagnostics plugin you were refering to?
https://this-week-in-neovim.org/2022/Jul/25#update-lsp_lines.nvim

**Comment by kkharji** [comment] 2022-08-01 21:07
> I just saw on this week in neovim, is that the diagnostics plugin you were refering to?
> https://this-week-in-neovim.org/2022/Jul/25#update-lsp_lines.nvim

Yes, it caught my attention because I wanted at some point to have multi virtual line for wiki plugin

**Comment by jbyuki** [comment] 2022-08-02 22:17
Hi @kkharji ,
I fixed the issue with the replace on the last delimiter. 
The replace on an empty line is kind of a dilemna. The issue is that it's possible to have wrapped delimiter `$$..$$` before and after the multi-line and nabla should take everything, and will error obviously. So I will leave it as is if you don't mind.

Also I'm really eager to try the virtual multi-line with nabla like you showed in this diagnostics plugin. It could be a nice alternative to the features nabla already offer (popup, replace, conceal, ...).

**Comment by kkharji** [comment] 2022-08-02 22:27
Thanks @jbyuki, sadly I begun to see why you start avoiding replace or slowly stop maintaining it. It doesn't make sense anymore with consideration to later preview in html to replace the values.

> Also I'm really eager to try the virtual multi-line with nabla like you showed in this diagnostics plugin. It could be a nice alternative to the features nabla already offer (popup, replace, conceal, ...).

Oh yah, I'd love that, so far my notes are unreadable 😭  

![Screen Shot 2022-08-03 at 1 22 29 AM](https://user-images.githubusercontent.com/65782666/182483626-4f89dc00-d6ae-44f1-a850-abbda44f660b.png)

I just hope the virtual multi-line would hide the latex and represent the textual representation. Maybe conceal is sufficient, I really don't know how virtual lines will turn out

**Comment by jbyuki** [comment] 2022-08-02 22:55
I was thinking about an annotation above the latex so that you can still go and edit the latex if needed easily. I will need to experiment a bit, but any suggestion is welcome of course.

**Closed by jbyuki** 2022-08-02 22:55 UTC

**Comment by jbyuki** [comment] 2022-08-10 21:42
See #35
